### ISSUE TITLE
database cache unserialization

### ISSUE THREAD

**Issue by EricWVGG** [simplepie/simplepie#146]
On a few cached feeds, I'm getting the following error:

A PHP Error was encountered
Severity: Notice
Message: unserialize() [function.unserialize]: Error at offset 5558 of 65535 bytes
Filename: Cache/MySQL.php
Line Number: 296

I haven't found a pattern to this issue yet. It has happened on these feeds:
http://threeminds.organic.com/atom.xml
http://secretforts.blogspot.com/feeds/posts/default?alt=rss

The problem continues to exist when I wipe the cache tables, and run the feeds twice more.

**Comment by ehb23** [comment]
I was also able to reproduce this bug and found a solution. 

Unfortunately the fix ifsnop suggested didn't work for me. Instead I encoded the data in base_64 and serialized/unserialized the content. The issue was resolved following my addition of the two functions base64_encode() and base64_decode() in MYSQL.php
