### ISSUE TITLE
Sanitize seems to expect output is HTML

### ISSUE THREAD

**Issue by morbus** [simplepie/simplepie#234]
G'day. Ran into this today. I'm parsing RSS/Atom feeds into a database, which is then used for, yes, display, but also other thingy things. Since all links are passed through SimplePIE sanitize(), the result that is getting saved in the database is an HTML-encoded URL and not one that is actually usable (say, on the command line, or passed to other applications).

So, it seems I need to run a decode-entities thing on the URL _before_ I save it to the database, and then just handle the re-encoding should I ever need to display the URL in an HTML source (something which my actual app framework already handles).

Anything else I should worry about?

How aggressive _is_ the sanitizer?

**Comment by mattoperry** [comment]
It seems to me that the problem is here:

https://github.com/simplepie/simplepie/blob/master/library/SimplePie/Sanitize.php#L370

```
if ($type & (SIMPLEPIE_CONSTRUCT_TEXT | SIMPLEPIE_CONSTRUCT_IRI))
{
	$data = htmlspecialchars($data, ENT_COMPAT, 'UTF-8');
}
```

which will cause the output of `$item->get_permalink()` to pass through `htmlspecialchars`.  Any thoughts about a mode where this is not the case?  i.e:  `SIMPLEPIE_CONSTRUCT_IRI_RAW` which would do the `absolutize_url ` stuff but not the `htmlspecialchars`?  I'm happy to PR this ... @rmccue ?
