### ISSUE TITLE
get_updated_date() doesn't return <atom:updated> 

### ISSUE THREAD

**Issue by SSilence** [simplepie/simplepie#376]
regarding #328 `get_updated_date()` should be used for getting atom_updated prior published. On following feed this doesn't work:
http://www.la-grange.net/feed

```
$parser->parse($this->data['date']['raw'])
```

in line 9792 always returns the published date.

**Comment by pierrrrrrre** [comment]
I'm writing a little follow-up in that issue since apparently this has not been looked at yet.

I'm still having troubles with this. 

If you check la-grange's feed today, you will see the last articles all have very different `published` and `updated` dates. For example, the last article published as of today:

```xml
<entry>
<id>tag:la-grange.net,2015-08-22:2015/08/22/marche</id>
<link rel="alternate" type="text/html" href="http://www.la-grange.net/2015/08/22/marche"></link><title>L'invitation d'une feuille</title>
<published>2015-08-22T23:59:00+09:00</published>
<updated>2015-10-11T12:42:00Z</updated>
…
```
I hope this issue can be addressed.

Thanks!

**Comment by pierrrrrrre** [comment]
@skyzyx:
I see this issue has been closed. Was it fixed? I don't see anything in the changelogs from the last releases that could refer to this...

Thanks!

**Comment by skyzyx** [comment]
No. I simply closed out issues that were either ancient, didn't have a PR, or have a low probability of ever being realistically added to SimplePie 1.x.

Sorry. 😬
