### ISSUE TITLE
Question: Code still up to date?

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#431]
Are this repo still maintained, and the code still up to date?
````Latest release, Oct 2012````, very few changes made after that, and there is a lot of old issues and pull requests...

I would like to switch to SimplePie, as I don't see that many competitors around, but I'm not sure if that's a good or bad thing to do. I've been maintaining and developing my own custom parser based on what once in a time was the _FeedForAll RSS2SQL_ parser, but I don't want to replace it with something that is not maintained anymore...

I've seen some forks is still active, is one of these the way to go? or does it exist any "new" semi-official repo somewhere intended to be a continuation?

**Comment by mblaney** [comment]
Hi @JanPetterMG I keep my fork up to date with the changes I'm making, depends if that suits what you want to use it for though. I would love to collaborate if you're interested.

**Comment by talgalili** [comment]
@mblaney - do you know of other people actively maintaining a fork?

Thanks.

**Comment by rmccue** [comment]
Sorry folks, I don't really have time to maintain this outside of security patches. However, I know there's a few people who are interested in continuing to maintain this. The state that I've left SP in is pretty unacceptable, so apologies to everyone using it.

@mblaney Happy to grant you with push access and all the bells-and-whistles if you'd like to help maintain it? (As a fellow Brisbanite, I instinctively trust you. ;) )

I'd like to add more people to help maintain it as well, since I don't have the resources to. I know @jgalea and team have been interested in this, and there's still lots of folks using SP, including WordPress. Ideally, 3-4 contributors could step up to help maintain the repo collaboratively.

The main thing I ask for any changes: **Don't break backwards compatibility** - BC must be maintained above (almost) everything else. Adding more stuff is fine, refactoring is fine, as is deprecating, but don't remove anything.

**Comment by talgalili** [comment]
Thanks @rmccue !

**Comment by ifsnop** [comment]
Please, don't let SP die!

On Fri, Mar 11, 2016 at 1:52 PM, Tal Galili <notifications@github.com>
wrote:

> Thanks @rmccue <https://github.com/rmccue> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simplepie/simplepie/issues/431#issuecomment-195353193>
> .
>



-- 
-- Use of a keyboard or mouse may be linked to serious injuries or
disorders.
diego dot torres at gmail dot com - Madrid / Spain

**Comment by mblaney** [comment]
hi @rmccue, thanks for the update. I'd be happy to take on some maintenance and agree that sharing the role with a few others with push access would be good.

I agree that there's no need to break backwards compatibility,  and the changes I've made haven't done that. Also a Brisbane SimplePie meetup might be good some time :-)

**Comment by rmccue** [comment]
> I'd be happy to take on some maintenance and agree that sharing the role with a few others with push access would be good.

Great; invite sent :)

If anyone else wants to step up, invitation is always open.

**Comment by ifsnop** [comment]
I have maintained an updated fork with fixes for a couple of years, but sad
because there were no upstream updates. I also develop other php tool
(mysqldump-php), and would like to help with SP.

**Comment by JanPetterMG** [comment]
@mblaney Thanks for the great work, I really appreciate it :+1:

**Comment by mblaney** [comment]
thanks for starting the conversation @JanPetterMG :-)

@ifsnop it would be great to have you on board! It doesn't look like I have permission to grant you access, so will leave that for @rmccue to add.

**Comment by rmccue** [comment]
Invite sent!
