### ISSUE TITLE
Found a feed that is not working

### ISSUE THREAD

**Issue by sfatfarma** [simplepie/simplepie#508]
Hello, I just found a feed that is not recognized by SimplePie. The feed address is: http://globalfamilydoctor.com/Syndication.aspx?rssid=2&rssparams=MMO%2bw77DvsO%2bw77DvjEyMMO%2bMTIww74%3d ; 
I have tested it here, and it is not found: http://simplepie.org/demo/?feed=http%3A%2F%2Fglobalfamilydoctor.com%2FSyndication.aspx%3Frssid%3D2%26rssparams%3DMMO%252bw77DvsO%252bw77DvjEyMMO%252bMTIww74%253d . 
Is this FAD or an issue? 
Sorry if FAD. 
Thank you!

**Comment by JanPetterMG** [comment]
The feed is valid, so there's probably an bug somewhere!
http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fglobalfamilydoctor.com%2FSyndication.aspx%3Frssid%3D2%26rssparams%3DMMO%252bw77DvsO%252bw77DvjEyMMO%252bMTIww74%253d

**Comment by sfatfarma** [comment]
Thank you for your response! Will be waiting for updates on this! Have a nice weekend!

**Comment by JanPetterMG** [comment]
Well, I'm able to parse it using my highly customized implementation of SimplePie, (witch is using the upcoming `1.5.0`, patched with the upcoming `1.4.4` fixes).
_The feed is fetched and decoded using an comprehensive GuzzleHttp implementation, the XML source code is going thru some extra checks before it's passed to `->set_raw_data($xml)`, and the encoding is parsed, modified and verified before it's (eventually) passed to `->set_input_encoding($encoding)`._

**So where's the bug?** Try using an different `User-agent`, and if you're on PHP7+, there is an url parsing bug (_I doubt that's the problem_, but that's why the php7 builds is failing). If none of those is the case, then there's another bug somewhere...

**Comment by sfatfarma** [comment]
Hello, I have PHP 5.5, so PHP7 is not the case. I tried to set different User-Agent but the same error was received. I set the UA with this command:
`$feed->set_useragent("Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36");
`
So no luck so far.

**Comment by bullride** [comment]
Hi @sfatfarma 
I checked the feed - Its working 100%
I entered the feed url you supplied with your original post & it's working 100% SEE SCREENSHOT
![screens](https://cloud.githubusercontent.com/assets/19853236/25069075/388bb306-2277-11e7-84fb-8b8d3d5ce329.png)

ALSO CHECK the URL at the very end - if you delete the " %3D " right at the end of your url THEN it does not work. SEE 2nd SCREENSHOT
![screensh](https://cloud.githubusercontent.com/assets/19853236/25069101/d9bc50dc-2277-11e7-88c5-bd696f16948e.png)

**Comment by sfatfarma** [comment]
Thank you very much for your response! It works! :)

**Comment by bullride** [comment]
, @sfatfarma @JanPetterMG 
NOT a problem Any time.
