### ISSUE TITLE
Migration to a HTTP library

### ISSUE THREAD

**Issue by jtojnar** [simplepie/simplepie#520]
Roadmap declares the intention to move from custom web fetcher to something more standardized. At selfoss, we are currently [in the process](https://github.com/SSilence/selfoss/pull/936) of doing the same so we would like to help with this for our dependencies, including SimplePie.

Since selfoss targets PHP 5.4, we would need to use older version of Guzzle (5.*), which might cause conflicts for applications using SimplePie and a different version of Guzzle. For this reason I propose depending on a [HTTPlug](http://httplug.io/) interface and letting the application choose the network library.

If you do not have any objections I will start working on it.

**Comment by mblaney** [comment]
no objections @jtojnar, @JanPetterMG do you use Guzzle with SimplePie? anything to add about implementing this?

**Comment by JanPetterMG** [comment]
I'm using Guzzle, version 6, with custom handlers and middlewares. It opens up a whole new world of options and possibilities, so I'm supporting this migration 110%.

I have a big wish, get rid of the [SimplePie_IRI](https://github.com/simplepie/simplepie/blob/master/library/SimplePie/IRI.php) class. Right now, the Travis builds are failing because of unsupported PHPunit version, but 3 of 4 failures for PHP 7 was due to bugs in that class. _(not sure where the last one was)._ Maybe we'll eventually see official PHP 7 support?

Actually, anyone can use whatever HTTP library they want already now, it's basically this easy:
```php
// Fetch the feed
$simplepie = new \SimplePie();
$simplepie->set_raw_data($xml);
// Parse the `content-type` header and set the encoding
// You MUST skip this if no encoding is provided, or you'll get parsing errors...
$simplepie->set_input_encoding($encoding);
$simplepie->init();
```
The above code has some drawbacks _(nothing that can't be handled externally)_
- Not possible to set an array of urls/feeds, and letting Simplepie merge them (automatically).
- No cache solution built in (`If-Modified-Since`, `ETag`, storage on disk/database)
- No feed auto-discovery, when parsing HTML to detect and redirect itself to an available XML feed

**Comment by skyzyx** [comment]
What I would recommend here is to dig in, and replace the `SimplePie_IRI` class all-together with the newer/better [Intl](http://php.net/Intl) extension.

**Comment by jtojnar** [comment]
For now, I am just overriding the `File` class: https://github.com/SSilence/selfoss/pull/1052

**Comment by Art4** [comment]
In like the idea. Since 2019 we have some new PSRs that could help us to allow any HTTP library:

- [PSR-7](https://www.php-fig.org/psr/psr-7/): HTTP message interfaces
- `[PSR-17](https://www.php-fig.org/psr/psr-17/)`: HTTP Factories
- [PSR-18](https://www.php-fig.org/psr/psr-18/): HTTP Client

Only downside: we would have to bump the min. PHP version to 7.2.
