### ISSUE TITLE
Namespaces broken if given as HTTPS

### ISSUE THREAD

**Issue by bkanber** [simplepie/simplepie#552]
When reading a feed with namespaces given as HTTPS SimplePie will not find the correct tags as it only matches HTTP namespaces. For instance: 

```
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="https://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="https://wellformedweb.org/CommentAPI/"
	xmlns:dc="https://purl.org/dc/elements/1.1/"
	xmlns:atom="https://www.w3.org/2005/Atom"
	xmlns:sy="https://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="https://purl.org/rss/1.0/modules/slash/"
	>
```

When calling `$item->get_content()` it will fall back to "description" even though "content:encoded" exists.

**Comment by skyzyx** [comment]
That’s because the namespace values themselves are documented as being HTTP instead of HTTPS. If you look at ththe Atom, Dublin Core, and other specs, their namespaces are all the non-TLS versions of the scheme.

So, that’s issue #1. Issue #2 is that with the way that SimplePie handles namespaces, it would be a fairly large and complex change to support this variation of the namespace URLs.

Your best bet would be to either ask the author to use the correctly-documented namespace URIs in their feed, or to use SimplePie_File directly to fetch the feed, use refer or XSLT to adjust the feed contents, then feed the updated XML into SimplePie.
