### ISSUE TITLE
XML_ERR_NAME_REQUIRED

### ISSUE THREAD

**Issue by jeffreyroberts** [simplepie/simplepie#555]
Another WordPress 4.8.2 RSS Feed Rejected

     http://businessinnovations.academy/feed/

Results in

    is invalid XML, likely due to invalid characters. XML error: XML_ERR_NAME_REQUIRED at line 1, column 2

**Comment by JanPetterMG** [comment]
No issues using the Simplepie demo.
http://simplepie.org/demo/?feed=http%3A%2F%2Fbusinessinnovations.academy%2Ffeed%2F

Not sure if the demo is up to date, but I had no problems myself either using v1.5.0

Sure your user-agent isn't being blocked by the server?

**Comment by jeffreyroberts** [comment]
I can see the feed...

Is the demo running on what composer would consider to be dev-master?

**Comment by JanPetterMG** [comment]
I doubt it, last time someone wrote it was updated, it was 1.4.x I think.
I'm on dev-master myself, custom setup, but no errors at all...

The only thing I can think of now, is an encoding detection issue, but that's just an wild guess...

**Comment by JanPetterMG** [comment]
Using commit d5c7b4dffa8811fd21471108126100b6389184ca (latest `dev-master`), the code below generates no errors at all. There is only one item in this feed, but no problems fetching any of the properties either...

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);

$feed = new SimplePie();
$feed->enable_cache(false);
$feed->set_feed_url('http://businessinnovations.academy/feed/');
$feed->init();
$error = $feed->error();
if (isset($error)) {
	var_export($error);
}
foreach ($feed->get_items() as $item) {
	// fetching various data, removed in this code snapshot
}
```

Related issues: #246, #280 and #300

Could you provide some code to reproduce?

**Comment by jeffreyroberts** [comment]
I am using RollingCurl to grab the feeds as fast as possible, Ive had good experiences with it in terms of crawling performance...

Here is my snippet

     $responseText = $request->getResponseText();

     $feed = new \SimplePie();
     $feed->set_raw_data($responseText);
     $goodFeed = $feed->init();

Here is the full error

    PHP Notice:  is invalid XML, likely due to invalid characters. XML error: XML_ERR_NAME_REQUIRED at line 1, column 2 in /Users/jlroberts/Projects/JeffreyLRobertsCom/Dashbored/vendor/simplepie/simplepie/library/SimplePie.php on line 1507

**Comment by JanPetterMG** [comment]
Ahh, similar setup as I'm using in my custom setup (except I'm using Guzzle instead).

You need to parse the headers, and set the encoding accordingly.
`$feed->set_input_encoding('UTF-8');`

**Comment by jeffreyroberts** [comment]
Word, I did `$feed->set_input_encoding('UTF-8');` but still the error persists, I havent gotten to parsing the headers yet, I am going to continue building this sample application, I should have it in a git repo momentarily

**Comment by jeffreyroberts** [comment]
lol, sample application works, it parses properly, let me see what the difference is between the text now

**Comment by jeffreyroberts** [comment]
I dont know what the difference is between the text, it looks the same to me... 

Let me plug #554 into the sample app now and see if it works...

**Comment by jeffreyroberts** [comment]
btw, thank you very much, setting the input encoding has removed a TON of errors from my application

**Comment by TheFirsh** [comment]
If anyone finds it useful I've run into a similar problem, so I'm just documenting my steps here. Let's assume there is nothing wrong with simplepie or WP. In case of a valid XML, the 2nd character is a `?` from `<?xml version="1.0" encoding="UTF-8"?>`. Yet the error mentions **"at line 1, column 2"**. In my case the server saw different data for an RSS feed than what I would in the browser. Guess what, the 2nd character was a `!` from a `<!DOCTYPE html>`. As the server ran into a captcha page of Vimeo in my case. So if your content is different for the server, and it's a fancy HTML error page, you'll get this ambigous error.

Solution was to perform HTTP request myself (with WordPress functions), then serve up the data on a silver platter to simplepie with [set_raw_data](http://simplepie.org/wiki/reference/simplepie/set_raw_data?rev=1182649516). This allows me to look into the response body and find out if it's even XML and show a more meaningful error if it's not. This can prevent simplepie from encountering a HTML page where you thought you've given it an XML (RSS).

Normally I'd use WP [fetch_feed](https://developer.wordpress.org/reference/functions/fetch_feed/) but even if it's possible to hook into it via `wp_feed_options,` it's soo url-based I wasn't sure how to get rid of it, so I created my own version. If setting the feed_url to something less meaningful, AND passing in data from the hook were possible, there would be no need of re-creating it.

`add_action('wp_feed_options', [$this, 'set_simplepie_options'], 20, 2);`

If the callback could accept arguments without an anyonymous function, it would be better. Because after I do the call, I want to remove my options of course.
