### ISSUE TITLE
Can't read Facebook RSS

### ISSUE THREAD

**Issue by CBox** [simplepie/simplepie#595]
I'm trying to parse Facebook Catalog RSS feed, it's in ATOM but not working for some reason:

FEED URL:
https://origincache.facebook.com/developers/resources/?id=dpa_product_catalog_sample_feed_atom.xml

```
$items = $feed->get_items();
$data = [];
foreach ($items as $item) {
	$data[] = [
		"title" => $item->get_title()
	];
}
```

The title is NULL.

**Comment by skyzyx** [comment]
That's because there isn't a `<title>` element; there is only a `<g:title>` element. The `g:` prefix is mapped to the Google Base namespace. Since SimplePie doesn't have built-in support for Google Base elements, it doesn't know how to read the value.

We would be happy to consider a patch if you wanted to provide one for Google Base.
