### ISSUE TITLE
[QUERY] 

### ISSUE THREAD

**Issue by mnaas** [simplepie/simplepie#636]
#### Description

I am just asking for help understanding the reason of this situation,
When I add this website to fetch its feed in the package "blog.codinghorror.com", I get the following error
"http://feeds.feedburner.com/codinghorror is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 10, column 8"
while using it in the simplepie demo gets the expected results.

Also, when I try to add the RSS URL directly in the package http://feeds.feedburner.com/codinghorror I get the following error:
"A feed could not be found at `http://feeds.feedburner.com/codinghorror`; the status code is `200` and content-type is `text/html; charset=UTF-8"
Still pasting it in the demo gets the expected results.

Why is this happening, and why I am not getting the same results as it shows in the demo page?

#### Environment
I was using v 1.5.3 and upgraded to 1.5.4 bit still with same errors.

**Comment by skyzyx** [comment]
> When I add this website to fetch its feed in the package "blog.codinghorror.com", I get the following error
"http://feeds.feedburner.com/codinghorror is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 10, column 8"
while using it in the simplepie demo gets the expected results.

99% of the time, this is a buggy version of libxml2 that your PHP is compiled with. This happens a lot with cheap shared hosting providers.

The solution is to compile your own with an up-to-date version of libxml2.

> Also, when I try to add the RSS URL directly in the package http://feeds.feedburner.com/codinghorror I get the following error:
"A feed could not be found at http://feeds.feedburner.com/codinghorror; the status code is 200 and content-type is `text/html; charset=UTF-8"
Still pasting it in the demo gets the expected results.

This is because `text/html` means that it’s a webpage, and not a feed. SimplePie doesn’t parse HTML, so it bails out when it encounters this.

If you want to force it to parse anyway, you need to call `$simplepie->force_feed()` before calling `$simplepie->init()`. This is how the demo is configured.
