### ISSUE TITLE
Make testsuite PHPUnit cross-version compatible

### ISSUE THREAD

**Issue by jrfnl** [simplepie/simplepie#663]
####  Is your feature request related to a problem? Please describe.

At this moment the tests can not be run on PHP 8.0/nightly, due to the supported PHPUnit version being limited to PHPUnit 5.x and 6.x, which are not compatible with PHP 8.0.

As PHP 8.0 was released last week, it would be kind of nice to make sure the tests pass on PHP 8.0.

#### Describe the solution you'd like

Due to debilitating breaking changes in various PHPUnit versions between the currently supported versions and PHPUnit 9.3, which is the first version officially compatible with PHP 8.0, making the test suite cross-version compatible is not trivial.

The easiest way to do it, would be by either using [Symfony PHPUnit Bridge](https://github.com/symfony/phpunit-bridge) or the [PHPUnit Polyfills](https://github.com/Yoast/PHPUnit-Polyfills/) package.

#### Additional context

If the maintainers of this package are open to the idea of making the test suite PHPUnit cross-version compatible by using the PHPUnit Polyfills package, I'd be willing to create a PR for this.

**Comment by jrfnl** [comment]
Anyone of the maintainers have an opinion on this ? The issue really becomes all the more urgent with the pletora of deprecation notices PHP 8.1 is throwing everywhere else. Would be nice to get some insight into the status of this repo ahead of the release.

With Travis dying an inglorious dead, I'd like to propose moving CI to GH Actions as well.

As I said above, I'm willing to put in the time & do the work, but would like the blessing of the maintainers for these proposals to prevent me wasting time.

/cc @mblaney @skyzyx

**Comment by skyzyx** [comment]
@mblaney is the current maintainer. I just pop in from time to time these days to help out with the backlog.

My opinion is that:

1. This is a good idea.

2. We should err on the side of fixing it "the right way" instead of "the hacky way". I don't know _precisely_ what that means in this context, but it's meant as _general_ guidance for how I'd like to see us move forward.

3. We should drop support for EOL'd PHP versions because they're EOL. IIRC, 7.3 goes EOL in November/December. Too many people are interested in "making it work"; not enough people are interested in asking "_should_ we be doing this?" Using EOL'd PHP is a Bad Idea™.

4. If the _community_ wants to see support maintained for EOL'd versions, and these polyfills help with that, so be it.

That said, I'm an alumnus and not the current maintainer. @mblaney would be handling whatever merges and ongoing maintenance comes in. Therefore, it's ultimately his call.

**Comment by jrfnl** [comment]
@skyzyx Thanks for pitching in!

I propose I'll start by sending in a PR to switch to GH Actions so at least CI will be up and running again once that is merged.

**Regarding the minimum supported version of PHP**: I'd like to put forward for consideration that WordPress is probably the biggest user of SimplePie and WordPress still has a minimum PHP version of PHP 5.6 (same as SimplePie currently has).

As thing stand, it does not look like WP will be changing that anytime soon (believe me, I've tried... I've tried so hard...), so continuing support for PHP 5.6, at least while the code is being made compatible with PHP 8.1 would be hugely appreciated.

**Regarding PHPUnit and the PHPUnit Polyfills**: the package was actually set up to be _not hacky_ (in contrast to Symfony PHPUnit Bridge, but that's just my opinion).
It uses only PHPUnit native functionality under the hood. It largely just provides wrappers for functionality changes and only if/when needed and then passes off to PHPUnit itself.

It is even [mentioned on the PHPUnit website](https://phpunit.de/supported-versions.html) (last paragraph) as the suggested way to make a test suite cross-version compatible if needed.

Let's hope @mblaney has a chance to comment soon as well.

**Comment by jrfnl** [comment]
PR #688 has been opened to address the switch from Travis to GH Actions to get the CI running again.

**Comment by mblaney** [comment]
sounds great @jrfnl thanks for taking it on

**Comment by jrfnl** [comment]
@mblaney Happy to help. Once PR #688 has been merged, I'll send in a PR to get the tests running on PHPUnit cross-version and we can see the results then in GH Actions to verify that the PR is okay.
