### ISSUE TITLE
SimplePie governance: Need more people with write access

### ISSUE THREAD

**Issue by Alkarex** [simplepie/simplepie#884]
Hello @skyzyx and @mblaney,
Merging even obvious pull requests has become much too slow in this SimplePie repo (e.g. https://github.com/simplepie/simplepie/pull/878#issuecomment-2351025383)
Meanwhile, there seems to be some [contributors doing a good job](https://github.com/simplepie/simplepie/graphs/contributors?from=01%2F01%2F2022), but without enough rights.

So to ensure continued development, motivation, reward contributors, and reduce the bus factor, please consider granting more rights to top contributors such as @jtojnar , @Art4 (if they are willing).

I can only see two people on https://github.com/orgs/simplepie/people - that is not enough.
I cannot see the roles, but there should be more owners / admins.

**Comment by skyzyx** [comment]
I haven't been a maintainer since 2010. But I own the organization. @mblaney has been the maintainer. @gsnedders and I are _emeritus_ status at this point.

If @mblaney, @jtojnar, and @Art4 agree to maintainership, I'm happy to grant more permissions. But I don't feel that this is my decision (anymore).

**Comment by jtojnar** [comment]
I am fine with sharing maintainership with @Art4.

I cannot promise to be super active, as I already maintain quite a few other projects so I tend to round-robin between them but the continuing evolution of SimplePie is important to me as one of the projects (selfoss rss reader) depends on SimplePie.

**Comment by Art4** [comment]
@Alkarex Thank you very much for considering me as a maintainer. I agree that more maintainer with write access will help the project move forward. I'm not very active at the moment because of some life changes but I'm still interested in investing more time into SimplePie in the near future. Seeing more PRs being merged will also increase my motivation. :slightly_smiling_face: 

Saying that I'm ready to take on more responsibility in cooperation with @jtojnar.

**Comment by skyzyx** [comment]
@mblaney: Any objections?

**Comment by mblaney** [comment]
hi everyone, sorry I've been unavailable recently. @skyzyx yes very happy to have more maintainers on board! I think the recent process of having people approve pr's before they're merged has been good and has made my job easier. If we stick to that I don't see any problems with others merging.

**Comment by Alkarex** [comment]
> process of having people approve pr's before they're merged has been good

Note that in GitHub's branch protection rule, it is possible to enforce that (among other things). It is also possible to auto-merge when the requirements are met

**Comment by skyzyx** [comment]
Invited @Art4 and @jtojnar to administer the `simplepie/simplepie` repository.

Welcome.
